# Generated by Django 3.2.7 on 2021-09-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_favoriterecipe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredients',
            unique_together={('ingredients', 'recipe')},
        ),
        migrations.AddConstraint(
            model_name='recipeingredients',
            constraint=models.UniqueConstraint(fields=('ingredients', 'recipe'), name='recipe_ingredients_unique'),
        ),
    ]
