# Generated by Django 3.2.7 on 2021-09-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_ingredient_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tittle',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='content',
        ),
        migrations.AddField(
            model_name='recipe',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('Завтрак', 'Завтрак'), ('Обед', 'Обед'), ('Ужин', 'Ужин')], max_length=20, verbose_name='meal time'),
        ),
    ]
